spring:
  application:
    name: flowmart
  aop:
    auto: true
  info:
    build:
      encoding: UTF-8
      location: classpath:META-INF/build-info.properties
  jackson:
    default-leniency: true
    locale: ${user.country}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: false
    banner-mode: console
    log-startup-info: true
    register-shutdown-hook: true
    keep-alive: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 500ms
    livereload:
      port: 35729
server:
  compression:
    enabled: true
    mime-types: */*
  port: 8080
  forward-headers-strategy: framework
logging:
  charset:
    console: UTF-8
  include-application-name: true
  level:
    root: info
    web: info
    com:
      shortthirdman: info
